---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3196689691-wdNaBHsOI6JbIlwIZeqRgU3hU1uS9ucdnuYnNQ1
:access_token_secret: b5vxpERJqotQCgvjwwSU9aOZQCUeZJc2bWQ5eoXJH6ZLS
